### ISSUE TITLE
Connection with MongoDB URI show's log messages

### ISSUE THREAD

**Issue by simonmilz** [cayasso/cacheman-mongo#17]
```js
const cache = new CachemanMongo(sails.config.connections.mongocache, {
  collection: 'cache'
});
```

this connection style shows the following output:

`the options [collection] is not supported`

**Comment by MrTechCenter** [comment]
I am getting the same output, that the [collection] option isn't supported, and have my connection set-up as such: 
`const CachemanMongo = require('cacheman-mongo');
var cache = new CachemanMongo(myMongoDBName, { collection: 'cache_name' });`

And because it's not accepting the [collections] option, when I try to pull data from the cache, it automatically tries to connect to a local instance of MongoDB which doesn't exist:
`{"MethodName":"retrieveKey","MethodPath":"cache.js","error":"failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]"}`

This problem didn't occur a week ago and nothing about my database, collection for caching, or this js file that I'm using CachemanMongo in have changed. I tried reinstalling CachemanMongo but I'm still getting the error. I know there's nothing wrong with the connection to my database itself because I'm using the same database in a different collection and it's working fine and I can also go directly into the collection for caching through the command prompt, so it's definitely accessible by my program. Any idea what could be causing this?

**Comment by MrTechCenter** [comment]
I tried creating the connection without the [collections] option so that it would just make a new collection in my database but it's still trying to connect to the default local database which obviously isn't there.  My "cache" variable is setup as mentioned above and my initialization of it is:

`cache.get('keyName', function (err, value) {`

I really don't see why this would simply stop working properly.

**Comment by cayasso** [comment]
1.0.4 is out with fix for this issue.

**Comment by simonmilz** [comment]
👍🏼
